### ISSUE TITLE
Oracle create NW user script is failing

### ISSUE THREAD

**Issue by timahenning** [saimachi/MCW-Migrating-Oracle-to-Azure-SQL-and-PostgreSQL#3]
![image](https://user-images.githubusercontent.com/48766586/131200287-8c78f50e-9b9c-49db-bb3c-27d1bd96b978.png)

**Comment by saimachi** [comment]
I recall this error. When you downloaded a ZIP archive of the lab files using the link in the lab, you downloaded the lab files from the Microsoft repository -- it does not contain the fix that I included to accommodate the containerized database engine (18c).

As you test my lab, I would advise you to clone my repository and navigate to the `september-2021-update` branch. The VM image already has Git installed. I didn't want to change the link in the lab, since once the updates are merged into the Microsoft lab, I would have to update the link again.

My branch not only contains a fix for this issue, but also corrects some data type incompatibilities that affect the migration stage, so it's important to use my files.
